1-1: main-1-1.cpp function-1-1.cpp
	g++ -Wall main-1-1.cpp function-1-1.cpp -o main-1-1
	./main-1-1

1-4: main-1-4.cpp function-1-4.cpp
	g++ -Wall main-1-4.cpp function-1-4.cpp -o main-1-4
	./main-1-4

1-5: main-1-5.cpp function-1-5.cpp
	g++ -Wall main-1-5.cpp function-1-5.cpp -o main-1-5
	./main-1-5

1-12: main-1-12.cpp function-1-12.cpp
	g++ -Wall function-1-12.cpp main-1-12.cpp -o main-1-12
	./main-1-12

2-1: main-2-1.cpp function-2-1.cpp
	g++ -Wall function-2-1.cpp main-2-1.cpp -o main-2-1
	./main-2-1

2-4: main-2-4.cpp function-2-4.cpp
	g++ -Wall function-2-4.cpp main-2-4.cpp -o main-2-4
	./main-2-4 < test-2-4.txt




